server:
  port: 9001


spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: nacos-payment-provider

# 将所有节点暴露
management:
  endpoints:
    web:
      exposure:
        include: '*'