server:
  port: 80

spring:
  application:
    name: consul-order-payment
  cloud:
    consul:
      host: localhost
      discovery:
        service-name: ${spring.application.name}
      port: 8500