server:
  port: 7002

eureka:
  instance:
    hostname: eureka701.com #服务端实例名称
  client:
    #false不向注册中心注册自己
    register-with-eureka: false
    #false表示自己端就是注册中心，职责负责维护服务实例，并不需要检索服务
    fetch-registry: false
    service-url:
      #设置与EUreka SErber交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka/